dist: xenial
sudo: required

language: php

php:
  - 'master'
  - '7.3.0RC1'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  depth: 1

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - libzip4
      - lcov

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  ccache: true
  timeout: 604800

compiler:
    - gcc

env:
  global:
    - CFLAGS="-ggdb -O0 -Wall -fvisibility=hidden"
    - REPORT_COVERAGE=1
    - REPORT_EXIT_STATUS=1
    - NO_INTERACTION=1

before_install:
  - travis_retry gem install coveralls-lcov
  - echo -e 'variables_order=EGPCS\nenable_dl=true' >> "$(phpenv root)/versions/$(phpenv version-name)/etc/php.ini"
  - echo -e 'opcache.enable=0\nopcache.enable_cli=0' >> "$(phpenv root)/versions/$(phpenv version-name)/etc/php.ini"
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - ulimit -c unlimited -S
  - sudo chmod +s $(which gdb)

install:
  - phpize
  - ./configure --with-php-config=$(phpenv which php-config) --enable-beanspeak CFLAGS="--coverage -fprofile-arcs -ftest-coverage $CFLAGS" LDFLAGS="--coverage"
  - make -j"$(getconf _NPROCESSORS_ONLN)"

before_script:
  - lcov --directory $(pwd)/beanspeak --directory $(pwd) --zerocounters
  - lcov --directory $(pwd)/beanspeak --directory $(pwd) --capture --compat-libtool --initial --output-file coverage.info
  - export TEST_PHP_EXECUTABLE=$(phpenv which php)

script:
  - $(phpenv which php) run-tests.php -d extension=beanspeak.so -d extension_dir=$(pwd)/modules -n $(pwd)/tests/*.phpt

jobs:
  include:
    - stage: Compillers testing
      php: 7.2
      compiler: clang
      env:
        - CFLAGS="-g -O0 -Wall -fvisibility=hidden"
        - CC=clang
      install:
        - phpize
        - ./configure --with-php-config=$(phpenv which php-config) --enable-beanspeak
        - make -j"$(getconf _NPROCESSORS_ONLN)"
      script:
        - export REPORT_COVERAGE=0
        - $(phpenv which php) run-tests.php -d extension=beanspeak.so -d extension_dir=$(pwd)/modules -n $(pwd)/tests/*.phpt

after_success:
  - |
      if [ "${REPORT_COVERAGE}" = "1" ]; then
        lcov --no-checksum --directory $(pwd)/beanspeak --directory $(pwd) --capture --compat-libtool --output-file coverage.info
        lcov --remove coverage.info "/usr*" --remove coverage.info "*/.phpenv/*" --remove coverage.info "/home/travis/build/include/*" --compat-libtool --output-file coverage.info
        coveralls-lcov coverage.info
      fi

after_failure:
  - $(phpenv which php) -v
  - $(phpenv which php) -m
  - for i in `find tests -name "*.out" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
  - for i in `find tests -name "*.mem" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
  - ./after_failure.sh

notifications:
  email: false
