dist: trusty
sudo: false

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

addons:
    apt:
        packages:
            - valgrind
            - gdb

cache:
    apt: true
    ccache: true
    timeout: 604800

git:
    depth: 1

compiler:
    - gcc
    - clang

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    exclude:
        - env: CC="gcc"
          compiler: clang
        - env: CC="clang"
          compiler: gcc

install:

script:

after_failure:
