dist: xenial
sudo: required

language: php

php:
  - 'master'
  - '7.3.0RC1'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  depth: 1

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - libzip4

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  ccache: true
  timeout: 604800

compiler:
    - gcc

env:
  global:
    - CFLAGS="-ggdb -O0 -Wall -fvisibility=hidden"
    - REPORT_EXIT_STATUS=1
    - ZEND_DONT_UNLOAD_MODULES=1
    - USE_ZEND_ALLOC=0

before_install:
  - echo -e 'variables_order=EGPCS\nenable_dl=true' >> "$(phpenv root)/versions/$(phpenv version-name)/etc/php.ini"
  - echo -e 'opcache.enable=0\nopcache.enable_cli=0' >> "$(phpenv root)/versions/$(phpenv version-name)/etc/php.ini"

install:
  - phpize
  - ./configure --with-php-config=$(phpenv which php-config) --enable-beanspeak
  - make -j"$(getconf _NPROCESSORS_ONLN)"

before_script:
  - sudo chmod +s $(which gdb)
  - ulimit -c unlimited -S

script:
  - php -d extension=$(pwd)/modules/beanspeak.so --ri beanspeak
  - make test

after_failure:
  - $(phpenv which php) -v
  - $(phpenv which php) -m
  - ./after_failure.sh

notifications:
  email: false
