dist: xenial
sudo: required

language: php

php:
  - 'master'
  - '7.3.0RC1'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  depth: 1

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - libzip4
      - lcov

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  ccache: true
  timeout: 604800

compiler:
    - gcc

env:
  global:
    - REPORT_COVERAGE=1
    - REPORT_EXIT_STATUS=1
    - NO_INTERACTION=1

before_install:
  - travis_retry gem install coveralls-lcov
  - echo -e 'variables_order=EGPCS\nenable_dl=true' >> "$(phpenv root)/versions/$(phpenv version-name)/etc/php.ini"
  - echo -e 'opcache.enable=0\nopcache.enable_cli=0' >> "$(phpenv root)/versions/$(phpenv version-name)/etc/php.ini"
  - ulimit -c unlimited -S
  - sudo chmod +s $(which gdb)

install:
  - phpize
  # However, the version of libtool that claims to no longer remove .gcno profiler information is libtool 2.2.6.
  # The fix is probably in later libtool versions as well.
  - aclocal && libtoolize --copy --force && autoreconf
  - ./configure --with-php-config=$(phpenv which php-config) --enable-beanspeak CFLAGS="--coverage -fprofile-arcs -ftest-coverage $CFLAGS" LDFLAGS="--coverage"
  - make -j"$(getconf _NPROCESSORS_ONLN)"

before_script:
  - lcov --directory $(pwd)/beanspeak --directory $(pwd) --zerocounters
  - lcov --directory $(pwd)/beanspeak --directory $(pwd) --capture --compat-libtool --initial --output-file coverage.info

script:
  - .ci/run-tests.sh

jobs:
  include:
    - stage: Compillers testing
      php: 7.2
      compiler: clang
      env:
        - CC=clang
      install:
        - phpize
        - ./configure --with-php-config=$(phpenv which php-config) --enable-beanspeak
        - make -j"$(getconf _NPROCESSORS_ONLN)"
      before_script:
      script:
        - export REPORT_COVERAGE=0; .ci/run-tests.sh

after_success:
  - .ci/after-success.sh

after_failure:
  - .ci/after-failure.sh

notifications:
  email: false
